// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: did_document_format.proto

package io.peaq.did;

public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:document.Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string controller = 2;</code>
   * @return The controller.
   */
  java.lang.String getController();
  /**
   * <code>string controller = 2;</code>
   * @return The bytes for controller.
   */
  com.google.protobuf.ByteString
      getControllerBytes();

  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  java.util.List<io.peaq.did.VerificationMethod> 
      getVerificationMethodsList();
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  io.peaq.did.VerificationMethod getVerificationMethods(int index);
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  int getVerificationMethodsCount();
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  java.util.List<? extends io.peaq.did.VerificationMethodOrBuilder> 
      getVerificationMethodsOrBuilderList();
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  io.peaq.did.VerificationMethodOrBuilder getVerificationMethodsOrBuilder(
      int index);

  /**
   * <code>.document.Signature signature = 4;</code>
   * @return Whether the signature field is set.
   */
  boolean hasSignature();
  /**
   * <code>.document.Signature signature = 4;</code>
   * @return The signature.
   */
  io.peaq.did.Signature getSignature();
  /**
   * <code>.document.Signature signature = 4;</code>
   */
  io.peaq.did.SignatureOrBuilder getSignatureOrBuilder();

  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  java.util.List<io.peaq.did.Service> 
      getServicesList();
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  io.peaq.did.Service getServices(int index);
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  int getServicesCount();
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  java.util.List<? extends io.peaq.did.ServiceOrBuilder> 
      getServicesOrBuilderList();
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  io.peaq.did.ServiceOrBuilder getServicesOrBuilder(
      int index);

  /**
   * <code>repeated string authentications = 6;</code>
   * @return A list containing the authentications.
   */
  java.util.List<java.lang.String>
      getAuthenticationsList();
  /**
   * <code>repeated string authentications = 6;</code>
   * @return The count of authentications.
   */
  int getAuthenticationsCount();
  /**
   * <code>repeated string authentications = 6;</code>
   * @param index The index of the element to return.
   * @return The authentications at the given index.
   */
  java.lang.String getAuthentications(int index);
  /**
   * <code>repeated string authentications = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the authentications at the given index.
   */
  com.google.protobuf.ByteString
      getAuthenticationsBytes(int index);
}
