// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: did_document_format.proto

package io.peaq.did;

/**
 * Protobuf type {@code document.Document}
 */
public final class Document extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:document.Document)
    DocumentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Document.newBuilder() to construct.
  private Document(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Document() {
    id_ = "";
    controller_ = "";
    verificationMethods_ = java.util.Collections.emptyList();
    services_ = java.util.Collections.emptyList();
    authentications_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Document();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.peaq.did.PeaqDidProto.internal_static_document_Document_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.peaq.did.PeaqDidProto.internal_static_document_Document_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.peaq.did.Document.class, io.peaq.did.Document.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTROLLER_FIELD_NUMBER = 2;
  private volatile java.lang.Object controller_;
  /**
   * <code>string controller = 2;</code>
   * @return The controller.
   */
  @java.lang.Override
  public java.lang.String getController() {
    java.lang.Object ref = controller_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      controller_ = s;
      return s;
    }
  }
  /**
   * <code>string controller = 2;</code>
   * @return The bytes for controller.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getControllerBytes() {
    java.lang.Object ref = controller_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      controller_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFICATIONMETHODS_FIELD_NUMBER = 3;
  private java.util.List<io.peaq.did.VerificationMethod> verificationMethods_;
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.peaq.did.VerificationMethod> getVerificationMethodsList() {
    return verificationMethods_;
  }
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.peaq.did.VerificationMethodOrBuilder> 
      getVerificationMethodsOrBuilderList() {
    return verificationMethods_;
  }
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  @java.lang.Override
  public int getVerificationMethodsCount() {
    return verificationMethods_.size();
  }
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  @java.lang.Override
  public io.peaq.did.VerificationMethod getVerificationMethods(int index) {
    return verificationMethods_.get(index);
  }
  /**
   * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
   */
  @java.lang.Override
  public io.peaq.did.VerificationMethodOrBuilder getVerificationMethodsOrBuilder(
      int index) {
    return verificationMethods_.get(index);
  }

  public static final int SIGNATURE_FIELD_NUMBER = 4;
  private io.peaq.did.Signature signature_;
  /**
   * <code>.document.Signature signature = 4;</code>
   * @return Whether the signature field is set.
   */
  @java.lang.Override
  public boolean hasSignature() {
    return signature_ != null;
  }
  /**
   * <code>.document.Signature signature = 4;</code>
   * @return The signature.
   */
  @java.lang.Override
  public io.peaq.did.Signature getSignature() {
    return signature_ == null ? io.peaq.did.Signature.getDefaultInstance() : signature_;
  }
  /**
   * <code>.document.Signature signature = 4;</code>
   */
  @java.lang.Override
  public io.peaq.did.SignatureOrBuilder getSignatureOrBuilder() {
    return getSignature();
  }

  public static final int SERVICES_FIELD_NUMBER = 5;
  private java.util.List<io.peaq.did.Service> services_;
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  @java.lang.Override
  public java.util.List<io.peaq.did.Service> getServicesList() {
    return services_;
  }
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.peaq.did.ServiceOrBuilder> 
      getServicesOrBuilderList() {
    return services_;
  }
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  @java.lang.Override
  public int getServicesCount() {
    return services_.size();
  }
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  @java.lang.Override
  public io.peaq.did.Service getServices(int index) {
    return services_.get(index);
  }
  /**
   * <code>repeated .document.Service services = 5;</code>
   */
  @java.lang.Override
  public io.peaq.did.ServiceOrBuilder getServicesOrBuilder(
      int index) {
    return services_.get(index);
  }

  public static final int AUTHENTICATIONS_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList authentications_;
  /**
   * <code>repeated string authentications = 6;</code>
   * @return A list containing the authentications.
   */
  public com.google.protobuf.ProtocolStringList
      getAuthenticationsList() {
    return authentications_;
  }
  /**
   * <code>repeated string authentications = 6;</code>
   * @return The count of authentications.
   */
  public int getAuthenticationsCount() {
    return authentications_.size();
  }
  /**
   * <code>repeated string authentications = 6;</code>
   * @param index The index of the element to return.
   * @return The authentications at the given index.
   */
  public java.lang.String getAuthentications(int index) {
    return authentications_.get(index);
  }
  /**
   * <code>repeated string authentications = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the authentications at the given index.
   */
  public com.google.protobuf.ByteString
      getAuthenticationsBytes(int index) {
    return authentications_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(controller_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, controller_);
    }
    for (int i = 0; i < verificationMethods_.size(); i++) {
      output.writeMessage(3, verificationMethods_.get(i));
    }
    if (signature_ != null) {
      output.writeMessage(4, getSignature());
    }
    for (int i = 0; i < services_.size(); i++) {
      output.writeMessage(5, services_.get(i));
    }
    for (int i = 0; i < authentications_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, authentications_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(controller_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, controller_);
    }
    for (int i = 0; i < verificationMethods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, verificationMethods_.get(i));
    }
    if (signature_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSignature());
    }
    for (int i = 0; i < services_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, services_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < authentications_.size(); i++) {
        dataSize += computeStringSizeNoTag(authentications_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAuthenticationsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.peaq.did.Document)) {
      return super.equals(obj);
    }
    io.peaq.did.Document other = (io.peaq.did.Document) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getController()
        .equals(other.getController())) return false;
    if (!getVerificationMethodsList()
        .equals(other.getVerificationMethodsList())) return false;
    if (hasSignature() != other.hasSignature()) return false;
    if (hasSignature()) {
      if (!getSignature()
          .equals(other.getSignature())) return false;
    }
    if (!getServicesList()
        .equals(other.getServicesList())) return false;
    if (!getAuthenticationsList()
        .equals(other.getAuthenticationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CONTROLLER_FIELD_NUMBER;
    hash = (53 * hash) + getController().hashCode();
    if (getVerificationMethodsCount() > 0) {
      hash = (37 * hash) + VERIFICATIONMETHODS_FIELD_NUMBER;
      hash = (53 * hash) + getVerificationMethodsList().hashCode();
    }
    if (hasSignature()) {
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
    }
    if (getServicesCount() > 0) {
      hash = (37 * hash) + SERVICES_FIELD_NUMBER;
      hash = (53 * hash) + getServicesList().hashCode();
    }
    if (getAuthenticationsCount() > 0) {
      hash = (37 * hash) + AUTHENTICATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getAuthenticationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.peaq.did.Document parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.peaq.did.Document parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.peaq.did.Document parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.peaq.did.Document parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.peaq.did.Document parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.peaq.did.Document parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.peaq.did.Document parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.peaq.did.Document parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.peaq.did.Document parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.peaq.did.Document parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.peaq.did.Document parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.peaq.did.Document parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.peaq.did.Document prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code document.Document}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:document.Document)
      io.peaq.did.DocumentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.peaq.did.PeaqDidProto.internal_static_document_Document_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.peaq.did.PeaqDidProto.internal_static_document_Document_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.peaq.did.Document.class, io.peaq.did.Document.Builder.class);
    }

    // Construct using io.peaq.did.Document.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      controller_ = "";

      if (verificationMethodsBuilder_ == null) {
        verificationMethods_ = java.util.Collections.emptyList();
      } else {
        verificationMethods_ = null;
        verificationMethodsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (signatureBuilder_ == null) {
        signature_ = null;
      } else {
        signature_ = null;
        signatureBuilder_ = null;
      }
      if (servicesBuilder_ == null) {
        services_ = java.util.Collections.emptyList();
      } else {
        services_ = null;
        servicesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      authentications_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.peaq.did.PeaqDidProto.internal_static_document_Document_descriptor;
    }

    @java.lang.Override
    public io.peaq.did.Document getDefaultInstanceForType() {
      return io.peaq.did.Document.getDefaultInstance();
    }

    @java.lang.Override
    public io.peaq.did.Document build() {
      io.peaq.did.Document result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.peaq.did.Document buildPartial() {
      io.peaq.did.Document result = new io.peaq.did.Document(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.controller_ = controller_;
      if (verificationMethodsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          verificationMethods_ = java.util.Collections.unmodifiableList(verificationMethods_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.verificationMethods_ = verificationMethods_;
      } else {
        result.verificationMethods_ = verificationMethodsBuilder_.build();
      }
      if (signatureBuilder_ == null) {
        result.signature_ = signature_;
      } else {
        result.signature_ = signatureBuilder_.build();
      }
      if (servicesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          services_ = java.util.Collections.unmodifiableList(services_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.services_ = services_;
      } else {
        result.services_ = servicesBuilder_.build();
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        authentications_ = authentications_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.authentications_ = authentications_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.peaq.did.Document) {
        return mergeFrom((io.peaq.did.Document)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.peaq.did.Document other) {
      if (other == io.peaq.did.Document.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getController().isEmpty()) {
        controller_ = other.controller_;
        onChanged();
      }
      if (verificationMethodsBuilder_ == null) {
        if (!other.verificationMethods_.isEmpty()) {
          if (verificationMethods_.isEmpty()) {
            verificationMethods_ = other.verificationMethods_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVerificationMethodsIsMutable();
            verificationMethods_.addAll(other.verificationMethods_);
          }
          onChanged();
        }
      } else {
        if (!other.verificationMethods_.isEmpty()) {
          if (verificationMethodsBuilder_.isEmpty()) {
            verificationMethodsBuilder_.dispose();
            verificationMethodsBuilder_ = null;
            verificationMethods_ = other.verificationMethods_;
            bitField0_ = (bitField0_ & ~0x00000001);
            verificationMethodsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVerificationMethodsFieldBuilder() : null;
          } else {
            verificationMethodsBuilder_.addAllMessages(other.verificationMethods_);
          }
        }
      }
      if (other.hasSignature()) {
        mergeSignature(other.getSignature());
      }
      if (servicesBuilder_ == null) {
        if (!other.services_.isEmpty()) {
          if (services_.isEmpty()) {
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureServicesIsMutable();
            services_.addAll(other.services_);
          }
          onChanged();
        }
      } else {
        if (!other.services_.isEmpty()) {
          if (servicesBuilder_.isEmpty()) {
            servicesBuilder_.dispose();
            servicesBuilder_ = null;
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000002);
            servicesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServicesFieldBuilder() : null;
          } else {
            servicesBuilder_.addAllMessages(other.services_);
          }
        }
      }
      if (!other.authentications_.isEmpty()) {
        if (authentications_.isEmpty()) {
          authentications_ = other.authentications_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureAuthenticationsIsMutable();
          authentications_.addAll(other.authentications_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              controller_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              io.peaq.did.VerificationMethod m =
                  input.readMessage(
                      io.peaq.did.VerificationMethod.parser(),
                      extensionRegistry);
              if (verificationMethodsBuilder_ == null) {
                ensureVerificationMethodsIsMutable();
                verificationMethods_.add(m);
              } else {
                verificationMethodsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getSignatureFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 34
            case 42: {
              io.peaq.did.Service m =
                  input.readMessage(
                      io.peaq.did.Service.parser(),
                      extensionRegistry);
              if (servicesBuilder_ == null) {
                ensureServicesIsMutable();
                services_.add(m);
              } else {
                servicesBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAuthenticationsIsMutable();
              authentications_.add(s);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object controller_ = "";
    /**
     * <code>string controller = 2;</code>
     * @return The controller.
     */
    public java.lang.String getController() {
      java.lang.Object ref = controller_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        controller_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string controller = 2;</code>
     * @return The bytes for controller.
     */
    public com.google.protobuf.ByteString
        getControllerBytes() {
      java.lang.Object ref = controller_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        controller_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string controller = 2;</code>
     * @param value The controller to set.
     * @return This builder for chaining.
     */
    public Builder setController(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      controller_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string controller = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearController() {
      
      controller_ = getDefaultInstance().getController();
      onChanged();
      return this;
    }
    /**
     * <code>string controller = 2;</code>
     * @param value The bytes for controller to set.
     * @return This builder for chaining.
     */
    public Builder setControllerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      controller_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.peaq.did.VerificationMethod> verificationMethods_ =
      java.util.Collections.emptyList();
    private void ensureVerificationMethodsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        verificationMethods_ = new java.util.ArrayList<io.peaq.did.VerificationMethod>(verificationMethods_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.peaq.did.VerificationMethod, io.peaq.did.VerificationMethod.Builder, io.peaq.did.VerificationMethodOrBuilder> verificationMethodsBuilder_;

    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public java.util.List<io.peaq.did.VerificationMethod> getVerificationMethodsList() {
      if (verificationMethodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(verificationMethods_);
      } else {
        return verificationMethodsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public int getVerificationMethodsCount() {
      if (verificationMethodsBuilder_ == null) {
        return verificationMethods_.size();
      } else {
        return verificationMethodsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public io.peaq.did.VerificationMethod getVerificationMethods(int index) {
      if (verificationMethodsBuilder_ == null) {
        return verificationMethods_.get(index);
      } else {
        return verificationMethodsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder setVerificationMethods(
        int index, io.peaq.did.VerificationMethod value) {
      if (verificationMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerificationMethodsIsMutable();
        verificationMethods_.set(index, value);
        onChanged();
      } else {
        verificationMethodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder setVerificationMethods(
        int index, io.peaq.did.VerificationMethod.Builder builderForValue) {
      if (verificationMethodsBuilder_ == null) {
        ensureVerificationMethodsIsMutable();
        verificationMethods_.set(index, builderForValue.build());
        onChanged();
      } else {
        verificationMethodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder addVerificationMethods(io.peaq.did.VerificationMethod value) {
      if (verificationMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerificationMethodsIsMutable();
        verificationMethods_.add(value);
        onChanged();
      } else {
        verificationMethodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder addVerificationMethods(
        int index, io.peaq.did.VerificationMethod value) {
      if (verificationMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerificationMethodsIsMutable();
        verificationMethods_.add(index, value);
        onChanged();
      } else {
        verificationMethodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder addVerificationMethods(
        io.peaq.did.VerificationMethod.Builder builderForValue) {
      if (verificationMethodsBuilder_ == null) {
        ensureVerificationMethodsIsMutable();
        verificationMethods_.add(builderForValue.build());
        onChanged();
      } else {
        verificationMethodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder addVerificationMethods(
        int index, io.peaq.did.VerificationMethod.Builder builderForValue) {
      if (verificationMethodsBuilder_ == null) {
        ensureVerificationMethodsIsMutable();
        verificationMethods_.add(index, builderForValue.build());
        onChanged();
      } else {
        verificationMethodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder addAllVerificationMethods(
        java.lang.Iterable<? extends io.peaq.did.VerificationMethod> values) {
      if (verificationMethodsBuilder_ == null) {
        ensureVerificationMethodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, verificationMethods_);
        onChanged();
      } else {
        verificationMethodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder clearVerificationMethods() {
      if (verificationMethodsBuilder_ == null) {
        verificationMethods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        verificationMethodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public Builder removeVerificationMethods(int index) {
      if (verificationMethodsBuilder_ == null) {
        ensureVerificationMethodsIsMutable();
        verificationMethods_.remove(index);
        onChanged();
      } else {
        verificationMethodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public io.peaq.did.VerificationMethod.Builder getVerificationMethodsBuilder(
        int index) {
      return getVerificationMethodsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public io.peaq.did.VerificationMethodOrBuilder getVerificationMethodsOrBuilder(
        int index) {
      if (verificationMethodsBuilder_ == null) {
        return verificationMethods_.get(index);  } else {
        return verificationMethodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public java.util.List<? extends io.peaq.did.VerificationMethodOrBuilder> 
         getVerificationMethodsOrBuilderList() {
      if (verificationMethodsBuilder_ != null) {
        return verificationMethodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(verificationMethods_);
      }
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public io.peaq.did.VerificationMethod.Builder addVerificationMethodsBuilder() {
      return getVerificationMethodsFieldBuilder().addBuilder(
          io.peaq.did.VerificationMethod.getDefaultInstance());
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public io.peaq.did.VerificationMethod.Builder addVerificationMethodsBuilder(
        int index) {
      return getVerificationMethodsFieldBuilder().addBuilder(
          index, io.peaq.did.VerificationMethod.getDefaultInstance());
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    public java.util.List<io.peaq.did.VerificationMethod.Builder> 
         getVerificationMethodsBuilderList() {
      return getVerificationMethodsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.peaq.did.VerificationMethod, io.peaq.did.VerificationMethod.Builder, io.peaq.did.VerificationMethodOrBuilder> 
        getVerificationMethodsFieldBuilder() {
      if (verificationMethodsBuilder_ == null) {
        verificationMethodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.peaq.did.VerificationMethod, io.peaq.did.VerificationMethod.Builder, io.peaq.did.VerificationMethodOrBuilder>(
                verificationMethods_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        verificationMethods_ = null;
      }
      return verificationMethodsBuilder_;
    }

    private io.peaq.did.Signature signature_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.peaq.did.Signature, io.peaq.did.Signature.Builder, io.peaq.did.SignatureOrBuilder> signatureBuilder_;
    /**
     * <code>.document.Signature signature = 4;</code>
     * @return Whether the signature field is set.
     */
    public boolean hasSignature() {
      return signatureBuilder_ != null || signature_ != null;
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     * @return The signature.
     */
    public io.peaq.did.Signature getSignature() {
      if (signatureBuilder_ == null) {
        return signature_ == null ? io.peaq.did.Signature.getDefaultInstance() : signature_;
      } else {
        return signatureBuilder_.getMessage();
      }
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     */
    public Builder setSignature(io.peaq.did.Signature value) {
      if (signatureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signature_ = value;
        onChanged();
      } else {
        signatureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     */
    public Builder setSignature(
        io.peaq.did.Signature.Builder builderForValue) {
      if (signatureBuilder_ == null) {
        signature_ = builderForValue.build();
        onChanged();
      } else {
        signatureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     */
    public Builder mergeSignature(io.peaq.did.Signature value) {
      if (signatureBuilder_ == null) {
        if (signature_ != null) {
          signature_ =
            io.peaq.did.Signature.newBuilder(signature_).mergeFrom(value).buildPartial();
        } else {
          signature_ = value;
        }
        onChanged();
      } else {
        signatureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     */
    public Builder clearSignature() {
      if (signatureBuilder_ == null) {
        signature_ = null;
        onChanged();
      } else {
        signature_ = null;
        signatureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     */
    public io.peaq.did.Signature.Builder getSignatureBuilder() {
      
      onChanged();
      return getSignatureFieldBuilder().getBuilder();
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     */
    public io.peaq.did.SignatureOrBuilder getSignatureOrBuilder() {
      if (signatureBuilder_ != null) {
        return signatureBuilder_.getMessageOrBuilder();
      } else {
        return signature_ == null ?
            io.peaq.did.Signature.getDefaultInstance() : signature_;
      }
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.peaq.did.Signature, io.peaq.did.Signature.Builder, io.peaq.did.SignatureOrBuilder> 
        getSignatureFieldBuilder() {
      if (signatureBuilder_ == null) {
        signatureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.peaq.did.Signature, io.peaq.did.Signature.Builder, io.peaq.did.SignatureOrBuilder>(
                getSignature(),
                getParentForChildren(),
                isClean());
        signature_ = null;
      }
      return signatureBuilder_;
    }

    private java.util.List<io.peaq.did.Service> services_ =
      java.util.Collections.emptyList();
    private void ensureServicesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        services_ = new java.util.ArrayList<io.peaq.did.Service>(services_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.peaq.did.Service, io.peaq.did.Service.Builder, io.peaq.did.ServiceOrBuilder> servicesBuilder_;

    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public java.util.List<io.peaq.did.Service> getServicesList() {
      if (servicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(services_);
      } else {
        return servicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public int getServicesCount() {
      if (servicesBuilder_ == null) {
        return services_.size();
      } else {
        return servicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public io.peaq.did.Service getServices(int index) {
      if (servicesBuilder_ == null) {
        return services_.get(index);
      } else {
        return servicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder setServices(
        int index, io.peaq.did.Service value) {
      if (servicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServicesIsMutable();
        services_.set(index, value);
        onChanged();
      } else {
        servicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder setServices(
        int index, io.peaq.did.Service.Builder builderForValue) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        services_.set(index, builderForValue.build());
        onChanged();
      } else {
        servicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder addServices(io.peaq.did.Service value) {
      if (servicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServicesIsMutable();
        services_.add(value);
        onChanged();
      } else {
        servicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder addServices(
        int index, io.peaq.did.Service value) {
      if (servicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServicesIsMutable();
        services_.add(index, value);
        onChanged();
      } else {
        servicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder addServices(
        io.peaq.did.Service.Builder builderForValue) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        services_.add(builderForValue.build());
        onChanged();
      } else {
        servicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder addServices(
        int index, io.peaq.did.Service.Builder builderForValue) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        services_.add(index, builderForValue.build());
        onChanged();
      } else {
        servicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder addAllServices(
        java.lang.Iterable<? extends io.peaq.did.Service> values) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, services_);
        onChanged();
      } else {
        servicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder clearServices() {
      if (servicesBuilder_ == null) {
        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        servicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public Builder removeServices(int index) {
      if (servicesBuilder_ == null) {
        ensureServicesIsMutable();
        services_.remove(index);
        onChanged();
      } else {
        servicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public io.peaq.did.Service.Builder getServicesBuilder(
        int index) {
      return getServicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public io.peaq.did.ServiceOrBuilder getServicesOrBuilder(
        int index) {
      if (servicesBuilder_ == null) {
        return services_.get(index);  } else {
        return servicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public java.util.List<? extends io.peaq.did.ServiceOrBuilder> 
         getServicesOrBuilderList() {
      if (servicesBuilder_ != null) {
        return servicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(services_);
      }
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public io.peaq.did.Service.Builder addServicesBuilder() {
      return getServicesFieldBuilder().addBuilder(
          io.peaq.did.Service.getDefaultInstance());
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public io.peaq.did.Service.Builder addServicesBuilder(
        int index) {
      return getServicesFieldBuilder().addBuilder(
          index, io.peaq.did.Service.getDefaultInstance());
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    public java.util.List<io.peaq.did.Service.Builder> 
         getServicesBuilderList() {
      return getServicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.peaq.did.Service, io.peaq.did.Service.Builder, io.peaq.did.ServiceOrBuilder> 
        getServicesFieldBuilder() {
      if (servicesBuilder_ == null) {
        servicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.peaq.did.Service, io.peaq.did.Service.Builder, io.peaq.did.ServiceOrBuilder>(
                services_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        services_ = null;
      }
      return servicesBuilder_;
    }

    private com.google.protobuf.LazyStringList authentications_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAuthenticationsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        authentications_ = new com.google.protobuf.LazyStringArrayList(authentications_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @return A list containing the authentications.
     */
    public com.google.protobuf.ProtocolStringList
        getAuthenticationsList() {
      return authentications_.getUnmodifiableView();
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @return The count of authentications.
     */
    public int getAuthenticationsCount() {
      return authentications_.size();
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param index The index of the element to return.
     * @return The authentications at the given index.
     */
    public java.lang.String getAuthentications(int index) {
      return authentications_.get(index);
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the authentications at the given index.
     */
    public com.google.protobuf.ByteString
        getAuthenticationsBytes(int index) {
      return authentications_.getByteString(index);
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param index The index to set the value at.
     * @param value The authentications to set.
     * @return This builder for chaining.
     */
    public Builder setAuthentications(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthenticationsIsMutable();
      authentications_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param value The authentications to add.
     * @return This builder for chaining.
     */
    public Builder addAuthentications(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthenticationsIsMutable();
      authentications_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param values The authentications to add.
     * @return This builder for chaining.
     */
    public Builder addAllAuthentications(
        java.lang.Iterable<java.lang.String> values) {
      ensureAuthenticationsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, authentications_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthentications() {
      authentications_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param value The bytes of the authentications to add.
     * @return This builder for chaining.
     */
    public Builder addAuthenticationsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAuthenticationsIsMutable();
      authentications_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:document.Document)
  }

  // @@protoc_insertion_point(class_scope:document.Document)
  private static final io.peaq.did.Document DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.peaq.did.Document();
  }

  public static io.peaq.did.Document getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Document>
      PARSER = new com.google.protobuf.AbstractParser<Document>() {
    @java.lang.Override
    public Document parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Document> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Document> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.peaq.did.Document getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

