// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: did_document_format.proto

package io.peaq.did;

public interface ServiceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:document.Service)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string serviceEndpoint = 3;</code>
   * @return The serviceEndpoint.
   */
  java.lang.String getServiceEndpoint();
  /**
   * <code>string serviceEndpoint = 3;</code>
   * @return The bytes for serviceEndpoint.
   */
  com.google.protobuf.ByteString
      getServiceEndpointBytes();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
