// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: did_document_format.proto

package io.peaq.did;

public interface SignatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:document.Signature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.document.VerificationType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.document.VerificationType type = 1;</code>
   * @return The type.
   */
  io.peaq.did.VerificationType getType();

  /**
   * <code>string issuer = 2;</code>
   * @return The issuer.
   */
  java.lang.String getIssuer();
  /**
   * <code>string issuer = 2;</code>
   * @return The bytes for issuer.
   */
  com.google.protobuf.ByteString
      getIssuerBytes();

  /**
   * <code>string hash = 3;</code>
   * @return The hash.
   */
  java.lang.String getHash();
  /**
   * <code>string hash = 3;</code>
   * @return The bytes for hash.
   */
  com.google.protobuf.ByteString
      getHashBytes();
}
