// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: did_document_format.proto

package io.peaq.did;

public interface VerificationMethodOrBuilder extends
    // @@protoc_insertion_point(interface_extends:document.VerificationMethod)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.document.VerificationType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.document.VerificationType type = 2;</code>
   * @return The type.
   */
  io.peaq.did.VerificationType getType();

  /**
   * <code>string controller = 3;</code>
   * @return The controller.
   */
  java.lang.String getController();
  /**
   * <code>string controller = 3;</code>
   * @return The bytes for controller.
   */
  com.google.protobuf.ByteString
      getControllerBytes();

  /**
   * <code>string publicKeyMultibase = 4;</code>
   * @return The publicKeyMultibase.
   */
  java.lang.String getPublicKeyMultibase();
  /**
   * <code>string publicKeyMultibase = 4;</code>
   * @return The bytes for publicKeyMultibase.
   */
  com.google.protobuf.ByteString
      getPublicKeyMultibaseBytes();
}
