//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: did_document_format.proto

package io.peaq.did;

@kotlin.jvm.JvmName("-initializedocument")
public inline fun document(block: io.peaq.did.DocumentKt.Dsl.() -> kotlin.Unit): io.peaq.did.Document =
  io.peaq.did.DocumentKt.Dsl._create(io.peaq.did.Document.newBuilder()).apply { block() }._build()
public object DocumentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.peaq.did.Document.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.peaq.did.Document.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.peaq.did.Document = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string controller = 2;</code>
     */
    public var controller: kotlin.String
      @JvmName("getController")
      get() = _builder.getController()
      @JvmName("setController")
      set(value) {
        _builder.setController(value)
      }
    /**
     * <code>string controller = 2;</code>
     */
    public fun clearController() {
      _builder.clearController()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class VerificationMethodsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
     public val verificationMethods: com.google.protobuf.kotlin.DslList<io.peaq.did.VerificationMethod, VerificationMethodsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getVerificationMethodsList()
      )
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     * @param value The verificationMethods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addVerificationMethods")
    public fun com.google.protobuf.kotlin.DslList<io.peaq.did.VerificationMethod, VerificationMethodsProxy>.add(value: io.peaq.did.VerificationMethod) {
      _builder.addVerificationMethods(value)
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     * @param value The verificationMethods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignVerificationMethods")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.peaq.did.VerificationMethod, VerificationMethodsProxy>.plusAssign(value: io.peaq.did.VerificationMethod) {
      add(value)
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     * @param values The verificationMethods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllVerificationMethods")
    public fun com.google.protobuf.kotlin.DslList<io.peaq.did.VerificationMethod, VerificationMethodsProxy>.addAll(values: kotlin.collections.Iterable<io.peaq.did.VerificationMethod>) {
      _builder.addAllVerificationMethods(values)
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     * @param values The verificationMethods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllVerificationMethods")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.peaq.did.VerificationMethod, VerificationMethodsProxy>.plusAssign(values: kotlin.collections.Iterable<io.peaq.did.VerificationMethod>) {
      addAll(values)
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     * @param index The index to set the value at.
     * @param value The verificationMethods to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setVerificationMethods")
    public operator fun com.google.protobuf.kotlin.DslList<io.peaq.did.VerificationMethod, VerificationMethodsProxy>.set(index: kotlin.Int, value: io.peaq.did.VerificationMethod) {
      _builder.setVerificationMethods(index, value)
    }
    /**
     * <code>repeated .document.VerificationMethod verificationMethods = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearVerificationMethods")
    public fun com.google.protobuf.kotlin.DslList<io.peaq.did.VerificationMethod, VerificationMethodsProxy>.clear() {
      _builder.clearVerificationMethods()
    }


    /**
     * <code>.document.Signature signature = 4;</code>
     */
    public var signature: io.peaq.did.Signature
      @JvmName("getSignature")
      get() = _builder.getSignature()
      @JvmName("setSignature")
      set(value) {
        _builder.setSignature(value)
      }
    /**
     * <code>.document.Signature signature = 4;</code>
     */
    public fun clearSignature() {
      _builder.clearSignature()
    }
    /**
     * <code>.document.Signature signature = 4;</code>
     * @return Whether the signature field is set.
     */
    public fun hasSignature(): kotlin.Boolean {
      return _builder.hasSignature()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ServicesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
     public val services: com.google.protobuf.kotlin.DslList<io.peaq.did.Service, ServicesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getServicesList()
      )
    /**
     * <code>repeated .document.Service services = 5;</code>
     * @param value The services to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addServices")
    public fun com.google.protobuf.kotlin.DslList<io.peaq.did.Service, ServicesProxy>.add(value: io.peaq.did.Service) {
      _builder.addServices(value)
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     * @param value The services to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignServices")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.peaq.did.Service, ServicesProxy>.plusAssign(value: io.peaq.did.Service) {
      add(value)
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     * @param values The services to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllServices")
    public fun com.google.protobuf.kotlin.DslList<io.peaq.did.Service, ServicesProxy>.addAll(values: kotlin.collections.Iterable<io.peaq.did.Service>) {
      _builder.addAllServices(values)
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     * @param values The services to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllServices")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.peaq.did.Service, ServicesProxy>.plusAssign(values: kotlin.collections.Iterable<io.peaq.did.Service>) {
      addAll(values)
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     * @param index The index to set the value at.
     * @param value The services to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setServices")
    public operator fun com.google.protobuf.kotlin.DslList<io.peaq.did.Service, ServicesProxy>.set(index: kotlin.Int, value: io.peaq.did.Service) {
      _builder.setServices(index, value)
    }
    /**
     * <code>repeated .document.Service services = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearServices")
    public fun com.google.protobuf.kotlin.DslList<io.peaq.did.Service, ServicesProxy>.clear() {
      _builder.clearServices()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AuthenticationsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string authentications = 6;</code>
     * @return A list containing the authentications.
     */
    public val authentications: com.google.protobuf.kotlin.DslList<kotlin.String, AuthenticationsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAuthenticationsList()
      )
    /**
     * <code>repeated string authentications = 6;</code>
     * @param value The authentications to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAuthentications")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AuthenticationsProxy>.add(value: kotlin.String) {
      _builder.addAuthentications(value)
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param value The authentications to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAuthentications")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AuthenticationsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param values The authentications to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAuthentications")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AuthenticationsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAuthentications(values)
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param values The authentications to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAuthentications")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AuthenticationsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string authentications = 6;</code>
     * @param index The index to set the value at.
     * @param value The authentications to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAuthentications")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AuthenticationsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setAuthentications(index, value)
    }/**
     * <code>repeated string authentications = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAuthentications")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AuthenticationsProxy>.clear() {
      _builder.clearAuthentications()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun io.peaq.did.Document.copy(block: io.peaq.did.DocumentKt.Dsl.() -> kotlin.Unit): io.peaq.did.Document =
  io.peaq.did.DocumentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val io.peaq.did.DocumentOrBuilder.signatureOrNull: io.peaq.did.Signature?
  get() = if (hasSignature()) getSignature() else null

