//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: did_document_format.proto

package io.peaq.did;

@kotlin.jvm.JvmName("-initializeservice")
public inline fun service(block: io.peaq.did.ServiceKt.Dsl.() -> kotlin.Unit): io.peaq.did.Service =
  io.peaq.did.ServiceKt.Dsl._create(io.peaq.did.Service.newBuilder()).apply { block() }._build()
public object ServiceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.peaq.did.Service.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.peaq.did.Service.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.peaq.did.Service = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string type = 2;</code>
     */
    public var type: kotlin.String
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>string type = 2;</code>
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * <code>string serviceEndpoint = 3;</code>
     */
    public var serviceEndpoint: kotlin.String
      @JvmName("getServiceEndpoint")
      get() = _builder.getServiceEndpoint()
      @JvmName("setServiceEndpoint")
      set(value) {
        _builder.setServiceEndpoint(value)
      }
    /**
     * <code>string serviceEndpoint = 3;</code>
     */
    public fun clearServiceEndpoint() {
      _builder.clearServiceEndpoint()
    }

    /**
     * <code>string data = 4;</code>
     */
    public var data: kotlin.String
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>string data = 4;</code>
     */
    public fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.peaq.did.Service.copy(block: io.peaq.did.ServiceKt.Dsl.() -> kotlin.Unit): io.peaq.did.Service =
  io.peaq.did.ServiceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

